version: '3.9'

services:
  TicketApi.Service:
    build:
      context: .
      dockerfile: ./TicketApi.Service/Dockerfile
    container_name: ticket-service
    restart: unless-stopped
    image: ghcr.io/demone415/ticketapi
    ports:
      - target: 80
        published: 11365
        protocol: tcp
        mode: ingress
      - target: 443
        published: 11366
        protocol: tcp
        mode: ingress
    networks:
      - 'tickets-network'
    environment:
      - 'CRED_REDIS=${CRED_REDIS}'
      - 'POSTGRES_HOMEAPI=${POSTGRES_LOCALHOST}'
      - 'PROVERKA_CHECKA_TOKEN=${PROVERKA_CHECKA_TOKEN}'
  
  TicketApi.Categorizer:
    build:
      context: .
      dockerfile: ./TicketApi.Categorizer/Dockerfile
    container_name: ticket-categorizer
    restart: unless-stopped
    image: ghcr.io/demone415/ticketcategorizer
    expose:
      - '80'
      - '443'
    networks:
      - 'tickets-network'

networks:
  'tickets-network':
    external: false
    name: ingress